[workspace]
authors = ["Luan Leal <luanric888@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "pygame"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.11,<3.14"
pgzero = ">=1.2.1,<2"
